apiVersion: v1
kind: Secret
metadata:
  name: controller-manager-token
  namespace: backup-system
  annotations:
    kubernetes.io/service-account.name: controller-manager
type: kubernetes.io/service-account-token
